/*
* @Author: detailyang
* @Date:   2016-02-26 13:53:51
* @Last Modified by:   detailyang
* @Last Modified time: 2016-02-29 09:58:11
*/

'use strict';
var bcrypt = require('bcrypt');

function check(plaintext, cipher) {
    return bcrypt.compareSync(plaintext, cipher)
}

function encrypt(plaintext, salt) {
    // oops, the salt should be generated by automate
    return bcrypt.hashSync(plaintext, salt);
}

module.exports = {
    check: check,
    encrypt: encrypt,
    genSalt: bcrypt.genSaltSync
};